# -*- coding: utf-8 -*-
"""imbd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FYz_RoyvLtJwUFUe8_hAHSyIdSyBC4FU
"""

from google.colab import files
import pandas as pd

# Upload your Excel file
uploaded = files.upload()

# Load dataset
file_name = list(uploaded.keys())[0]
df = pd.read_excel(file_name)

# Display info
print("✅ File loaded successfully!")
print(df.head())
print(df['sentiment'].value_counts())

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense, Dropout
from sklearn.metrics import confusion_matrix, classification_report

# Load dataset (top 10k words)
vocab_size = 10000
maxlen = 200

(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=vocab_size)

# Pad sequences to equal length
X_train = pad_sequences(X_train, maxlen=maxlen)
X_test = pad_sequences(X_test, maxlen=maxlen)

print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)

model = Sequential([
    Embedding(vocab_size, 128, input_length=maxlen),
    SimpleRNN(128, return_sequences=True, activation='tanh'),
    Dropout(0.3),
    SimpleRNN(64, return_sequences=False, activation='tanh'),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.2),
    Dense(1, activation='sigmoid')
])

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

history = model.fit(
    X_train, y_train,
    epochs=20,
    batch_size=128,
    validation_data=(X_test, y_test),
    verbose=1
)

loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"\n✅ Test Accuracy: {accuracy*100:.2f}%")

# Generate predictions
y_pred = (model.predict(X_test) > 0.5).astype("int32")

# Create confusion matrix
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.show()

print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=['Negative', 'Positive']))

import pickle

# -------------------------------
# 📈 Plot Accuracy & Loss Curves
# -------------------------------
plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Val Accuracy')
plt.title('Accuracy Over Epochs')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()

plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.title('Loss Over Epochs')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.show()

# -------------------------------
# 💾 Save Model & Tokenizer
# -------------------------------

# Save trained RNN model
model.save("rnn_imdb.h5")
print("✅ Model saved successfully as rnn_imdb.h5")

# Save tokenizer for future use (to convert text → sequence)
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(num_words=10000)
tokenizer.fit_on_texts(["placeholder"])  # Dummy fit so object is initialized
with open("tokenizer.pkl", "wb") as f:
    pickle.dump(tokenizer, f)
print("✅ Tokenizer saved successfully as tokenizer.pkl")

from tensorflow.keras.models import load_model
import pickle

model = load_model("rnn_imdb.h5")

with open("tokenizer.pkl", "rb") as f:
    tokenizer = pickle.load(f)

from google.colab import files
files.download('rnn_imdb.h5')
files.download('tokenizer.pkl')

